dist: bionic
language: python
python:
  - "3.8"
sudo: required
services:
  - docker

before_install:
  - touch .env
  - echo 'DOCKER_OPTS="${DOCKER_OPTS} --registry-mirror=https://mirror.gcr.io"' | sudo tee -a /etc/default/docker
  - sudo service docker restart

install:
  - docker pull python:3.9-buster
  - docker-compose build

before_script:
  - docker-compose up -d

script:
  # Put test code here
  - docker-compose exec server pipenv run mypy /app/

notifications:
  email: false
