dist: bionic
language: python
python:
  - "3.8"

services:
  - docker

before_install:
  - touch .env

install:
  - docker pull python:3.9-buster
  - docker-compose build

before_script:
  - docker-compose up -d

script:
  # Put test code here
  - docker-compose exec server pipenv run mypy /app/

notifications:
  email: false
