dist: bionic
language: python
python:
  - "3.8"

services:
  - docker

before_install:
  - touch .env
  - echo 'DOCKER_OPTS="--registry-mirror=https://mirror.gcr.io"' | sudo tee -a /etc/default/docker
  - sudo restart docker

install:
  - docker-compose build

before_script:
  - docker-compose up -d

script:
  # Put test code here
  - docker-compose exec server pipenv run mypy /app/

notifications:
  email: false
