FROM python:3.9-buster

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - && \
    apt-get update && \
    apt-get install -y nodejs && \
    pip install pipenv==2020.11.15 && \
    apt-get clean

ENV APP_DIR=/app
WORKDIR $APP_DIR

RUN apt-get update && apt-get install -y wait-for-it && apt-get clean

#COPY app/package.json app/package-lock.json $APP_DIR/
#RUN npm install

COPY app/Pipfile app/Pipfile.lock $APP_DIR/
RUN pipenv install --dev
