#!/usr/bin/env bash

# See https://sipb.mit.edu/doc/safe-shell/
set -euf -o pipefail

if [ -t 1 ]; then
  export NORMAL=$(tput setaf 0)
  export RED=$(tput setaf 1)
  export GREEN=$(tput setaf 2)
  export YELLOW=$(tput setaf 3)
  export BLUE=$(tput setaf 4)
  export MAGENTA=$(tput setaf 5)
  export CYAN=$(tput setaf 6)
  export WHITE=$(tput setaf 7)
  export BOLD=$(tput bold)
  export REVERSE=$(tput rev)
  export RESET=$(tput sgr0)
else
  export NORMAL=""
  export RED=""
  export GREEN=""
  export YELLOW=""
  export BLUE=""
  export MAGENTA=""
  export CYAN=""
  export WHITE=""
  export BOLD=""
  export REVERSE=""
  export RESET=""
fi

echo "${GREEN}${BOLD}Hi! I'm here to setup your new project${RESET}"
echo "${CYAN}Creating a .env file${RESET}"
touch .env
echo "Environment File Created"
