# Generated by Django 3.1.6 on 2021-02-09 14:58

import common.enums
import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_party_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='political_party',
            field=common.fields.EnumField(default='Dem', enum=common.enums.PoliticalParty),
        ),
    ]
